#!/usr/bin/env ruby

#
# your best ahan manager ever.
#

require 'date'

option    = ARGV[0] 
ahan_file = ARGV[1]

ahan_dir = "/usr/local/etc/.nrop/"
unless File.directory?(ahan_dir)
  system "mkdir -p #{ahan_dir}"
end

def ahan_files(ahan_dir)
  Dir["#{ahan_dir}/*"]
end

case option
when "-z"
  abort "you need file name"     unless ahan_file
  abort "you need mp4 as input." unless ahan_file.end_with?(".mp4")
  ahan_file_encrypted = DateTime.now.to_s.gsub(/[:\-\+]/, "")
  system "cp #{ahan_file} #{File.basename(ahan_file)}"
  system "zip -r #{ahan_file_encrypted}.zip #{File.basename(ahan_file)}"
  system "mv #{ahan_file_encrypted}.zip #{ahan_dir}/#{ahan_file_encrypted}"
  system "rm #{File.basename(ahan_file)}"
when "-o"
  zips = ahan_files(ahan_dir)
  zips.each_with_index do |zip, i|
    puts "[#{i}] #{zip}"
  end
  print "which: "
  i = $stdin.gets.chomp
  ahan = zips[i.to_i]
  system "cp #{ahan} #{ahan}.zip" 
  system "unzip #{ahan}" 
  system "rm #{ahan}.zip" 
  mp4 = ahan_files(".").select{|ahan| ahan.end_with?(".mp4")}.first
  system "open /Applications/QuickTime\\ Player.app/ #{mp4}"
  system "rm #{mp4}"
when "-h", "--help"
  puts
  puts "ahan [-z] yourahan.mp4 .... encrypt your ahan"
  puts "ahan [-o]              .... watch your ahan"
  puts
else
end


