#!/usr/bin/env ruby

#
# your best porn manager ever.
#

require 'date'

option    = ARGV[0] 
porn_file = ARGV[1]

porn_dir = "/usr/local/etc/nrop/"
unless File.directory?(porn_dir)
  system "mkdir -p #{porn_dir}"
end

def porn_files(porn_dir)
  Dir["#{porn_dir}/*"]
end

def mom_cleans_up_your_mess(mp4)
  print "[press enter after watching:] "
  $stdin.gets.chomp
  system "rm #{mp4}"
  puts "now your porn is gone. have a good day!"
end

case option
when "-z"
  abort "you need mp4 as input." unless porn_file.end_with?(".mp4")
  porn_file_encrypted = DateTime.now.to_s.gsub(/[:\-\+]/, "")
  system "zip -r #{porn_file_encrypted}.zip #{porn_file}"
  system "mv #{porn_file_encrypted}.zip #{porn_dir}/#{porn_file_encrypted}"
  system "rm #{porn_file}"
when "-o"
  zips = porn_files(porn_dir)
  zips.each_with_index do |zip, i|
    puts "[#{i}] #{zip}"
  end
  print "which: "
  i = $stdin.gets.chomp
  porn = zips[i.to_i]
  system "cp #{porn} #{porn}.zip" 
  system "unzip #{porn}" 
  system "rm #{porn}.zip" 
  mp4 = porn_files(".").select{|porn| porn.end_with?(".mp4")}.first
  system "open /Applications/QuickTime\\ Player.app/ #{mp4}"
  mom_cleans_up_your_mess mp4
when "-h", "--help"
  puts
  puts "porn [-z] yourporn.mp4 .... encrypt your porn"
  puts "porn [-o]              .... watch your porn"
  puts
else
end


